database-tests:
  runs-on: ubuntu-latest
  needs: frontend-tests
  services:
    postgres:
      image: postgres:14
      env:
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
        POSTGRES_DB: test_db
      ports:
        - 5432:5432
      options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Set up Python 3.10
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install pytest

  - name: Run database tests
    env:
      DATABASE_URL: postgresql://test:test@localhost:5432/test_db
    run: pytest app/tests/database
